name: Continuos Delivery
on:
  push:
    branches:
      - main #qualquer branch

jobs:
  deliver:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Simulação Cont Delivery
        uses: actions/upload-artifact@v4
        with:

          name: Arquivotest.zip

          path: |
            **.py
            README.md


  deploy:
    runs-on: windows-latest

    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Arquivotest.zip
          
      - name: Display dowload files
        run: ls -r
      

  #docker:
  #  needs: deploy
  #  runs-on: ubunto-latest
  #  steps:
  #    -
  #      name: Checkout
  #      uses: actions/checkout@v4
  #    -
  #      # Add support for more platforms with QEMU (optional)
  #      # https://github.com/docker/setup-qemu-action
  #      name: Set up QEMU
  #      uses: docker/setup-qemu-action@v3
  #    -
  #      name: Set up Docker Buildx
  #      uses: docker/setup-buildx-action@v3


