name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: test com pytest
        run: |
          pip install pytest pytest-cov pytest-asyncio 
          pytest tests/Test.py --disable-warnings -q --tb=short

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
